spring:
  application:
    name: todo-litst-api
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

jwt:
  secret: ${JWT_SECRET:this-is-a-very-long-secret-key-for-testing-purposes}
