spring:
  application:
    name: todo-litst-api
  config:
    import: optional:file:.env[.properties]
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

jwt:
  secret: ${JWT_SECRET}
